# Generated by Django 6.1.1 on 2026-09-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cliente_crm_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agendaappointment',
            new_name='api_agendaa_date_1fd2d1_idx',
            old_name='api_agendaa_date_7a1c0e_idx',
        ),
        migrations.RenameIndex(
            model_name='agendaappointment',
            new_name='api_agendaa_staff_i_4d8f2f_idx',
            old_name='api_agendaa_staff_i_8f2b1a_idx',
        ),
    ]
