# Generated by Django 6.1.1 on 2026-09-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_api_agendaa_date_7a1c0e_idx_api_agendaa_date_1fd2d1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendastaff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff/'),
        ),
    ]
