# Generated by Django 6.1.1 on 2026-09-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_agendastaff_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('excerpt', models.TextField(help_text='Resumen corto para la tarjeta del listado')),
                ('body', models.TextField(help_text='Cuerpo del artículo (párrafos separados por línea en blanco)')),
                ('category', models.CharField(choices=[('prevencion', 'Prevención'), ('tecnico', 'Técnico'), ('curiosidades', 'Curiosidades'), ('salud', 'Salut Ambiental')], default='prevencion', max_length=32)),
                ('author', models.CharField(default='Equipo Técnico CECSA', max_length=120)),
                ('image', models.CharField(blank=True, default='/assets/cockroach-focus.webp', help_text='Ruta pública (ej. /assets/…) o URL absoluta', max_length=400)),
                ('read_time_minutes', models.PositiveSmallIntegerField(default=5)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artículo de blog',
                'verbose_name_plural': 'Artículos de blog',
                'ordering': ['-published_at', '-id'],
            },
        ),
    ]
