# Generated by Django 6.1.1 on 2026-09-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_commercial_content_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='body',
            field=models.TextField(help_text='Cuerpo del artículo en Markdown'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='policies_ca',
            field=models.TextField(blank=True, default="Empresa familiar ètica i conscient amb més de 20 anys d'experiència. En els casos habituals treballem amb diagnòstic, dues actuacions i seguiment. Inspecció gratuïta en zona de cobertura. No oferim servei fora de Catalunya. La garantia de solució s'aplica segons condicions del pressupost (accés, instruccions i abast contractat). No cobreix noves entrades des de veïns, baixants o zones no tractades."),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='policies_es',
            field=models.TextField(blank=True, default='Empresa familiar ética y consciente con más de 20 años de experiencia. En los casos habituales trabajamos con diagnóstico, dos actuaciones y seguimiento. Inspección gratuita en zona de cobertura. No ofrecemos servicio fuera de Catalunya. La garantía de solución aplica según condiciones del presupuesto (acceso, instrucciones y alcance contratado). No cubre nuevas entradas desde vecinos, bajantes o zonas no tratadas.'),
        ),
    ]
