# Generated by Django 6.1.1 on 2026-09-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_cuc_ger_piso_price_240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaservicio',
            name='reglas_comerciales',
            field=models.JSONField(default=list, help_text='[{"condition": {"field": "metros_cuadrados", "op": "lt", "value": 80}, "precio_venta": 240}, …]'),
        ),
    ]
