# Generated by Django 5.x

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_adminmessage_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="IgeoMirrorEntity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source_key",
                    models.CharField(
                        help_text="tipo:codigo o tipo:remote:id — clave estable de upsert",
                        max_length=180,
                        unique=True,
                    ),
                ),
                ("entity_type", models.CharField(db_index=True, max_length=64)),
                ("igeo_codigo", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                (
                    "remote_operation_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=128),
                ),
                ("comando", models.CharField(blank=True, default="", max_length=16)),
                ("display_name", models.CharField(blank=True, default="", max_length=255)),
                ("telefono", models.CharField(blank=True, default="", max_length=32)),
                ("telefono_norm", models.CharField(blank=True, db_index=True, default="", max_length=15)),
                ("email", models.CharField(blank=True, default="", max_length=254)),
                ("direccion", models.CharField(blank=True, default="", max_length=255)),
                ("localidad", models.CharField(blank=True, default="", max_length=120)),
                ("estado", models.CharField(blank=True, default="", max_length=64)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("source", models.CharField(db_index=True, default="export", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="igeo_mirror_entities",
                        to="api.cliente",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="igeomirrorentity",
            index=models.Index(fields=["entity_type", "igeo_codigo"], name="api_igeomir_entity__idx"),
        ),
        migrations.AddIndex(
            model_name="igeomirrorentity",
            index=models.Index(fields=["entity_type", "is_deleted"], name="api_igeomir_entity__del_idx"),
        ),
    ]
