-- Optimized for CECSA Backend
-- Following supabase-postgres-best-practices skill

-- 1. Services Table
CREATE TABLE IF NOT EXISTS public.api_service (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    icon VARCHAR(50) NOT NULL,
    color VARCHAR(20) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_service_title ON public.api_service(title);

-- 2. Contact Submissions Table
CREATE TABLE IF NOT EXISTS public.api_contactsubmission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_contact_created_at ON public.api_contactsubmission(created_at DESC);

-- Enable RLS
ALTER TABLE public.api_service ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.api_contactsubmission ENABLE ROW LEVEL SECURITY;

-- 3. Security Policies (RLS)
CREATE POLICY "Allow public read access to services" 
ON public.api_service FOR SELECT 
TO public 
USING (true);

CREATE POLICY "Allow public inserts to contact submissions" 
ON public.api_contactsubmission FOR INSERT 
TO public 
WITH CHECK (true);

CREATE POLICY "Allow authenticated users to read submissions" 
ON public.api_contactsubmission FOR SELECT 
TO authenticated 
USING (true);

COMMENT ON TABLE public.api_service IS 'Stores pest control services for Cecsa website.';
COMMENT ON TABLE public.api_contactsubmission IS 'Stores leads from the contact form.';
